"""scripts/ci/check_attribution.py: commits and pull requests credit no AI assistant."""

import importlib.util
import json
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location(
    "check_attribution", ROOT / "scripts/ci/check_attribution.py"
)
check = importlib.util.module_from_spec(spec)
spec.loader.exec_module(check)


@pytest.mark.parametrize(
    "line",
    [
        "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>",
        "co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>",
        "Co-authored-by: Codex <codex@openai.com>",
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
        "Generated by ChatGPT",
        "Reviewed-by: someone <noreply@anthropic.com>",
    ],
)
def test_assistant_credits_are_found(line):
    assert check.attributions(f"fix: a thing\n\nBody.\n\n{line}\n") == [line]


@pytest.mark.parametrize(
    "text",
    [
        "docs: AGENTS.md as the one instruction file for Claude, Codex and Copilot",
        "Adds Claude Code read-only permissions.",
        "Co-authored-by: Arjun Ganesh <iarjunganesh@users.noreply.github.com>",
        "The summary is generated from the changelog.",
    ],
)
def test_mentions_and_human_co_authors_pass(text):
    assert check.attributions(text) == []


def git(repo, *args):
    command = ["git", *args]  # git from PATH, in a throwaway repository
    subprocess.run(command, cwd=repo, check=True, capture_output=True)  # noqa: S603


@pytest.fixture
def repo(tmp_path, monkeypatch):
    git(tmp_path, "init", "-q", "-b", "main")
    git(tmp_path, "config", "user.name", "Maintainer")
    git(tmp_path, "config", "user.email", "maintainer@example.com")
    git(tmp_path, "commit", "-q", "--allow-empty", "-m", "base")
    git(tmp_path, "tag", "base")
    monkeypatch.chdir(tmp_path)
    return tmp_path


def test_each_commit_in_the_range_is_checked(repo, capsys):
    git(repo, "commit", "-q", "--allow-empty", "-m", "clean")
    git(
        repo,
        "commit",
        "-q",
        "--allow-empty",
        "-m",
        "feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
    )

    assert check.main(["base", "HEAD"]) == 1
    out = capsys.readouterr().out
    assert out.count("commit ") == 1 and "Co-Authored-By: Claude" in out


def test_a_clean_range_passes(repo, monkeypatch, capsys):
    monkeypatch.delenv("GITHUB_EVENT_PATH", raising=False)
    git(repo, "commit", "-q", "--allow-empty", "-m", "fix: y\n\nA body that names Claude.")

    assert check.main(["base"]) == 0
    assert "No AI attribution in base..HEAD" in capsys.readouterr().out


def test_the_pull_request_description_is_checked(repo, tmp_path, monkeypatch, capsys):
    event = tmp_path / "event.json"
    event.write_text(json.dumps({"pull_request": {"body": "Notes\n\nGenerated with Claude Code"}}))
    monkeypatch.setenv("GITHUB_EVENT_PATH", str(event))

    assert check.main(["base", "HEAD"]) == 1
    assert "pull request description: Generated with Claude Code" in capsys.readouterr().out


def test_events_without_a_description_check_commits_only(tmp_path):
    push = tmp_path / "push.json"
    push.write_text(json.dumps({"ref": "refs/heads/main"}))
    empty = tmp_path / "empty.json"
    empty.write_text(json.dumps({"pull_request": {"body": None}}))

    assert check.pull_request_body(None) is None
    assert check.pull_request_body(str(push)) is None
    assert check.pull_request_body(str(empty)) == ""
