"""Emit the light and dark variants of every hand-authored SVG master, and its raster exports.

Run from the repository root:

    uv run python scripts/ci/render_assets.py            # variants, then PNG/GIF if tools exist
    uv run python scripts/ci/render_assets.py --check    # CI: variants current, palettes pass AA
    uv run python scripts/ci/render_assets.py --no-raster

**Why variants exist.** Each master carries a light palette and a dark palette inside a
`prefers-color-scheme` media query. That query does not help on GitHub: a README image is an
`<img>`, and an SVG inside `<img>` does not follow the page's theme. So the README uses a
`<picture>` element with one file per theme, and this script writes those files from the
master. Nothing is maintained twice by hand.

**What `--check` enforces.**

1. Every `-light.svg` / `-dark.svg` matches what its master would emit now.
2. Every text/background pair a master declares in its `/* CONTRAST ... */` comment meets WCAG
   AA (4.5:1) in both palettes, using the project's own `accessibility/wcag.py`.

**Rasters are not checked.** PNG stills and GIFs need a Chromium browser and ffmpeg, which CI
does not have, and two renders are not byte-identical. The SVG variants are the source; the
rasters are exports for places that cannot show SVG (the GitHub social preview, articles,
slides).

**How frames are taken.** Each frame is an HTML page with the SVG inlined, which pauses the
SMIL timeline and seeks it to the frame's time, then one headless browser screenshot. Every
animation duration in the masters divides LOOP_SECONDS, so the GIF loops without a jump, and
frame 0 carries the full meaning on its own.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

from argus.accessibility.wcag import WCAGLevel, contrast_ratio  # noqa: E402

SOURCES = (ROOT / "assets" / "brand", ROOT / "assets" / "architecture")

LIGHT_BLOCK = re.compile(r"/\* PALETTE:LIGHT \*/(.*?)/\* /PALETTE:LIGHT \*/", re.DOTALL)
DARK_BLOCK = re.compile(r"/\* PALETTE:DARK \*/(.*?)/\* /PALETTE:DARK \*/", re.DOTALL)
MEDIA_WRAPPER = re.compile(r"@media \(prefers-color-scheme: dark\) \{(.*)\}", re.DOTALL)
TOKEN = re.compile(r"--([\w-]+)\s*:\s*(#[0-9A-Fa-f]{6})\b")
CONTRAST = re.compile(r"/\* CONTRAST (.*?)\*/", re.DOTALL)
SIZE = re.compile(r'<svg[^>]*\bwidth="(\d+)"[^>]*\bheight="(\d+)"')

GENERATED = "<!-- GENERATED by scripts/ci/render_assets.py from {master}. Do not edit. -->"
GENERATED_LINE = re.compile(r"^<!-- GENERATED by .*-->\n", re.MULTILINE)

LOOP_SECONDS = 6
FPS = 12.5
FRAMES = int(LOOP_SECONDS * FPS)
WORKERS = 6

# Which raster exports each master gets, per theme. Everything else is SVG only.
RASTERS: dict[str, dict[str, tuple[str, ...]]] = {
    "social-preview": {"png": ("dark",)},
    "banner-16x9": {"png": ("dark", "light"), "gif": ("dark", "light")},
    "system-overview": {"png": ("dark", "light")},
    "investigation-flow": {"png": ("dark", "light"), "gif": ("dark", "light")},
    "v2-target": {"png": ("dark", "light")},
}

BROWSERS = (
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    "microsoft-edge",
    "chromium",
    "google-chrome",
)

FRAME_PAGE = """<!doctype html><html><head><style>
html,body{{margin:0;padding:0;overflow:hidden}}
</style></head><body>
{svg}
<script>
var svg = document.querySelector("svg");
svg.pauseAnimations();
svg.setCurrentTime({t});
</script></body></html>"""


def masters() -> list[Path]:
    """Every SVG with palette sentinels that is not itself an emitted variant."""
    found = []
    for directory in SOURCES:
        for path in sorted(directory.glob("*.svg")):
            if path.stem.endswith(("-light", "-dark")):
                continue
            if LIGHT_BLOCK.search(path.read_text(encoding="utf-8")):
                found.append(path)
    return found


def palettes(source: str, name: str) -> tuple[str, str]:
    """The light and dark palette declarations of a master, dark one unwrapped."""
    light = LIGHT_BLOCK.search(source)
    dark = DARK_BLOCK.search(source)
    if light is None or dark is None:
        raise SystemExit(f"{name}: missing PALETTE:LIGHT / PALETTE:DARK sentinels")
    inner = MEDIA_WRAPPER.search(dark.group(1))
    if inner is None:
        raise SystemExit(f"{name}: the dark palette is not wrapped in a media query")
    return light.group(1), inner.group(1)


def variant(source: str, name: str, *, dark: bool) -> str:
    light_palette, dark_palette = palettes(source, name)
    light = LIGHT_BLOCK.search(source)
    dark_block = DARK_BLOCK.search(source)
    assert light is not None and dark_block is not None
    palette = dark_palette if dark else light_palette
    out = source[: light.start()] + palette + source[dark_block.end() :]
    return out.replace("<svg ", GENERATED.format(master=name) + "\n<svg ", 1)


def contrast_problems(source: str, name: str) -> list[str]:
    """Check each declared text/background token pair in both palettes against WCAG AA."""
    declared = CONTRAST.search(source)
    if declared is None:
        return [f"{name}: no /* CONTRAST ... */ declaration"]
    pairs = [pair.split(":") for pair in declared.group(1).split()]
    problems = []
    for theme, palette in zip(("light", "dark"), palettes(source, name), strict=True):
        tokens = dict(TOKEN.findall(palette))
        for fg, bg in pairs:
            if fg not in tokens or bg not in tokens:
                problems.append(f"{name} ({theme}): unknown token in pair {fg}:{bg}")
                continue
            ratio = contrast_ratio(tokens[fg], tokens[bg])
            if ratio < WCAGLevel.AA.value:
                problems.append(
                    f"{name} ({theme}): --{fg} on --{bg} is {ratio:.2f}:1, need "
                    f"{WCAGLevel.AA.value}:1"
                )
    return problems


# ── rasters ───────────────────────────────────────────────────────────────────


def tool(candidates: tuple[str, ...]) -> str | None:
    for candidate in candidates:
        if Path(candidate).exists():
            return candidate
        found = shutil.which(candidate)
        if found:
            return found
    return None


def run(argv: list[str], *, timeout: int) -> bool:
    try:
        completed = subprocess.run(argv, capture_output=True, timeout=timeout, check=False)
    except subprocess.TimeoutExpired, OSError:
        return False
    return completed.returncode == 0


def capture(body: str, t: float, size: tuple[int, int], browser: str, target: Path) -> bool:
    page = target.with_suffix(".html")
    page.write_text(FRAME_PAGE.format(svg=body, t=round(t, 4)), encoding="utf-8")
    ok = run(
        [
            browser,
            "--headless",
            "--disable-gpu",
            "--hide-scrollbars",
            "--force-device-scale-factor=1",
            f"--window-size={size[0]},{size[1]}",
            f"--screenshot={target}",
            page.resolve().as_uri(),
        ],
        timeout=120,
    )
    return ok and target.exists()


def render(svg: Path, kinds: set[str], browser: str, ffmpeg: str) -> list[Path]:
    text = GENERATED_LINE.sub("", svg.read_text(encoding="utf-8"))
    match = SIZE.search(text)
    if match is None:
        raise SystemExit(f"{svg.name}: the <svg> element needs width and height attributes")
    size = (int(match.group(1)), int(match.group(2)))
    written = []
    with tempfile.TemporaryDirectory(prefix="argus-render-") as raw:
        work = Path(raw)
        count = FRAMES if "gif" in kinds else 1
        with ThreadPoolExecutor(max_workers=WORKERS) as pool:
            done = list(
                pool.map(
                    lambda i: capture(text, i / FPS, size, browser, work / f"frame{i:03d}.png"),
                    range(count),
                )
            )
        if not all(done):
            print(f"  {svg.stem}: {done.count(False)} frame(s) failed to render")
            return written
        if "png" in kinds:
            shutil.copyfile(work / "frame000.png", svg.with_suffix(".png"))
            written.append(svg.with_suffix(".png"))
        if "gif" in kinds and assemble_gif(work, svg.with_suffix(".gif"), ffmpeg):
            written.append(svg.with_suffix(".gif"))
    return written


def assemble_gif(work: Path, target: Path, ffmpeg: str) -> bool:
    """Frames to GIF through a palette built from what changes between frames, undithered.

    Most of each frame is static, so dithering would make every frame differ everywhere and
    defeat inter-frame compression; the artwork is flat fills, so banding is not visible.
    """
    return run(
        [
            ffmpeg,
            "-y",
            "-v",
            "error",
            "-framerate",
            str(FPS),
            "-i",
            str(work / "frame%03d.png"),
            "-vf",
            "split[a][b];[a]palettegen=stats_mode=diff[p];"
            "[b][p]paletteuse=dither=none:diff_mode=rectangle",
            "-loop",
            "0",
            str(target),
        ],
        timeout=300,
    )


# ── entry point ───────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail on stale variants or contrast")
    parser.add_argument("--no-raster", action="store_true", help="skip PNG and GIF exports")
    parser.add_argument("--only", help="render rasters only for masters whose name contains this")
    args = parser.parse_args()

    found = masters()
    if not found:
        print("::error::no SVG masters with palette sentinels found")
        return 1

    problems: list[str] = []
    variants: list[tuple[Path, Path, str]] = []
    for master in found:
        source = master.read_text(encoding="utf-8")
        problems.extend(contrast_problems(source, master.name))
        for theme in ("light", "dark"):
            target = master.with_name(f"{master.stem}-{theme}.svg")
            expected = variant(source, master.name, dark=theme == "dark")
            variants.append((master, target, theme))
            if args.check:
                current = target.read_text(encoding="utf-8") if target.exists() else ""
                if current != expected:
                    problems.append(f"{target.relative_to(ROOT).as_posix()} is stale")
            else:
                target.write_text(expected, encoding="utf-8", newline="\n")

    if problems:
        for problem in problems:
            print(f"::error::{problem}")
        if args.check:
            print("Fix the master, then run: uv run python scripts/ci/render_assets.py")
        return 1
    if args.check:
        print(f"Asset variants are current and pass WCAG AA ({len(found)} masters).")
        return 0
    print(f"Wrote {len(variants)} variants from {len(found)} masters.")

    if args.no_raster:
        return 0
    browser, ffmpeg = tool(BROWSERS), tool(("ffmpeg",))
    if browser is None or ffmpeg is None:
        print("Skipped PNG/GIF exports: a Chromium browser and ffmpeg are both required.")
        return 0
    for master, target, theme in variants:
        wanted = {kind for kind, themes in RASTERS.get(master.stem, {}).items() if theme in themes}
        if not wanted or (args.only and args.only not in master.stem):
            continue
        for path in render(target, wanted, browser, ffmpeg):
            print(f"  {path.relative_to(ROOT).as_posix()}  {path.stat().st_size / 1024:.0f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
